export const users = [
	{ userId: "u1", userName: "Алексей_1994b" },
	{ userId: "u2", userName: "Джунбокс3000" },
	{ userId: "u3", userName: "Семен Иванов" },
	{ userId: "u4", userName: "Максим Авдеенко" },
	{ userId: "u6", userName: "Жоржетта Картохина" },
	{ userId: "u10", userName: "Жорж Картохин" },
];

export const mockData = [
	{
		id: "c1",
		text: "Самое обидное когда сценарий по сути есть - в виде книг, где нет сюжетных дыр, всё логично, стройное повествование и достаточно взять и экранизировать оригинал как это было в первых фильмах с минимальным количеством отсебятины и зритель с восторгом примет любой такой фильм и сериал, однако вместо этого 'Кольца власти' просто позаимствовали имена из оригинала, куски истории, мало связанные между собой и выдали очередной среднячковый сериал на один раз в лучшем случае.",
		userName: "Алексей_1994b",
		userId: "u1",
		commentType: "comment",
		commentTime: "15.01 13:55",
		commentTimestamp: 1673780100,
		rating: 1,
		like: false,
		raters: [{ userId: "u2", rateState: 1 }],
		answers: ["c2"],
		parentId: null,
	},
	{
		id: "c2",
		text: "Наверное, самая большая ошибка создателей сериала была в том, что они поставили уж слишком много надежд на поддержку фанатов вселенной. Как оказалось на деле, большинство 'фанатов' с самой настоящей яростью и желчью стали уничтожать сериал, при этом объективности в отзывах самый минимум.",
		userName: "Джунбокс3000",
		userId: "u2",
		commentType: "answer",
		commentTime: "15.01 15:18",
		commentTimestamp: 1673785080,
		rating: 0,
		like: false,
		raters: [],
		answers: [],
		parentId: "c1",
	},
	{
		id: "c3",
		text: "И я того же мнения",
		userName: "Семен Иванов",
		userId: "u3",
		commentType: "comment",
		commentTime: "15.01 16:20",
		commentTimestamp: 1673788800,
		rating: -1,
		like: false,
		raters: [{ userId: "u6", rateState: -1 }],
		answers: ["c8"],
		parentId: null,
	},
	{
		id: "c8",
		text: "Ну естественно",
		userName: "Жоржетта Картохина",
		userId: "u6",
		commentType: "answer",
		commentTime: "15.01 16:50",
		commentTimestamp: 1673790600,
		rating: 0,
		like: false,
		raters: [],
		answers: [],
		parentId: "c3",
	},
	{
		id: "c4",
		text: "Здравствуйте",
		userName: "Жорж Картохин",
		userId: "u10",
		commentType: "comment",
		commentTime: "15.01 16:50",
		commentTimestamp: 1673790600,
		rating: 0,
		like: false,
		raters: [],
		answers: [],
		parentId: null,
	},
];
